### ISSUE TITLE
nu.stream object not working properly

### ISSUE THREAD

**Issue by danielleamya** [ircam-cosima/soundworks-nu#2]
Hi,
I am having issues with the nu.stream object in this library. The getting-started patch works just fine and so do a couple of others, but I can't get the nu.stream object to play audio coming from the adc. It worked briefly for some reason yesterday, but the audio was very crunchy and not true to the original recording. Am I doing something wrong? Is there more that needs to be added to the helper patch?

Thanks!

**Comment by PyrApple** [comment]
Of all the Nü modules, the nu.stream is the one that’s more of a PoC than a usable module as is (not efficient by far for multi-client streaming). 

if your goal is:
1) multi-cast stream, I’d advise to use a dedicated javascript module.
2) single client stream, I will look in the nu.stream object since this simple scenario should work.

**Comment by danielleamya** [comment]
Okay thanks!
